### ISSUE TITLE
Could you share all the proposals generated by the WSPN? 

### ISSUE THREAD

**Issue by ShenghaiRong** [Vibashan/Mask-free-OVIS#2]
Thanks for your great work and for sharing the code. However, the proposals provided for the COCO base set are incomplete. Could you share all the COCO proposals generated by WSPN or the Selective Search proposals for COCO?

**Comment by Vibashan** [comment]
Hi @ShenghaiRong ,

Sorry for the delayed response; as mentioned in the paper I followed [https://github.com/NVlabs/wetectron](https://github.com/NVlabs/wetectron) repo to generate the WSPN proposal. 

For selective search, I followed [https://github.com/ChenjieXu/selective_search](https://github.com/ChenjieXu/selective_search) to generate the selective search proposals.

Do multi-thread for selective search to get quicker results.
